[tool.black]
line-length = 120
target-version = ['py310']

[tool.pyright]
pythonVersion="3.10"
reportMissingImports=false
reportInvalidTypeVarUse=false
reportMissingModuleSource=false
pythonPlatform="Linux"
